# coding: utf-8

from __future__ import absolute_import

from sarna.routes.api import util
from sarna.routes.api.models.base_model_ import Model


class AssessmentType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    WEB = "Web"
    EXTERNAL_PENTEST = "External_pentest"
    MOBILE = "Mobile"
    IOS = "iOS"
    ANDROID = "Android"
    WIFI = "WiFi"

    def __init__(self):  # noqa: E501
        """AssessmentType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'AssessmentType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AssessmentType of this AssessmentType.  # noqa: E501
        :rtype: AssessmentType
        """
        return util.deserialize_model(dikt, cls)
