# coding: utf-8

from __future__ import absolute_import

from sarna.routes.api import util
from sarna.routes.api.models.base_model_ import Model


class AssessmentStatus(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    OPEN = "Open"
    CLOSED = "Closed"
    ARCHIVED = "Archived"

    def __init__(self):  # noqa: E501
        """AssessmentStatus - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'AssessmentStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AssessmentStatus of this AssessmentStatus.  # noqa: E501
        :rtype: AssessmentStatus
        """
        return util.deserialize_model(dikt, cls)
