# coding: utf-8

from __future__ import absolute_import

from typing import List  # noqa: F401

from sarna.routes.api import util
from sarna.routes.api.models.base_model_ import Model


class ClientRequestBody(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, short_name=None, long_name=None, managers=None):  # noqa: E501
        """ClientRequestBody - a model defined in OpenAPI

        :param short_name: The short_name of this ClientRequestBody.  # noqa: E501
        :type short_name: str
        :param long_name: The long_name of this ClientRequestBody.  # noqa: E501
        :type long_name: str
        :param managers: The managers of this ClientRequestBody.  # noqa: E501
        :type managers: List[str]
        """
        self.openapi_types = {
            'short_name': str,
            'long_name': str,
            'managers': List[str]
        }

        self.attribute_map = {
            'short_name': 'short_name',
            'long_name': 'long_name',
            'managers': 'managers'
        }

        self._short_name = short_name
        self._long_name = long_name
        self._managers = managers

    @classmethod
    def from_dict(cls, dikt) -> 'ClientRequestBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ClientRequestBody of this ClientRequestBody.  # noqa: E501
        :rtype: ClientRequestBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def short_name(self):
        """Gets the short_name of this ClientRequestBody.


        :return: The short_name of this ClientRequestBody.
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name):
        """Sets the short_name of this ClientRequestBody.


        :param short_name: The short_name of this ClientRequestBody.
        :type short_name: str
        """
        if short_name is None:
            raise ValueError("Invalid value for `short_name`, must not be `None`")  # noqa: E501
        if short_name is not None and len(short_name) > 64:
            raise ValueError("Invalid value for `short_name`, length must be less than or equal to `64`")  # noqa: E501

        self._short_name = short_name

    @property
    def long_name(self):
        """Gets the long_name of this ClientRequestBody.


        :return: The long_name of this ClientRequestBody.
        :rtype: str
        """
        return self._long_name

    @long_name.setter
    def long_name(self, long_name):
        """Sets the long_name of this ClientRequestBody.


        :param long_name: The long_name of this ClientRequestBody.
        :type long_name: str
        """
        if long_name is None:
            raise ValueError("Invalid value for `long_name`, must not be `None`")  # noqa: E501
        if long_name is not None and len(long_name) > 128:
            raise ValueError("Invalid value for `long_name`, length must be less than or equal to `128`")  # noqa: E501

        self._long_name = long_name

    @property
    def managers(self):
        """Gets the managers of this ClientRequestBody.


        :return: The managers of this ClientRequestBody.
        :rtype: List[str]
        """
        return self._managers

    @managers.setter
    def managers(self, managers):
        """Sets the managers of this ClientRequestBody.


        :param managers: The managers of this ClientRequestBody.
        :type managers: List[str]
        """

        self._managers = managers
