# coding: utf-8

from __future__ import absolute_import

from sarna.routes.api import util
from sarna.routes.api.models.base_model_ import Model


class Envelop(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None, error=None):  # noqa: E501
        """Envelop - a model defined in OpenAPI

        :param data: The data of this Envelop.  # noqa: E501
        :type data: object
        :param error: The error of this Envelop.  # noqa: E501
        :type error: Error
        """
        from sarna.routes.api.models import Error
        self.openapi_types = {
            'data': object,
            'error': Error
        }

        self.attribute_map = {
            'data': 'data',
            'error': 'error'
        }

        self._data = data
        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> 'Envelop':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Envelop of this Envelop.  # noqa: E501
        :rtype: Envelop
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this Envelop.


        :return: The data of this Envelop.
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this Envelop.


        :param data: The data of this Envelop.
        :type data: object
        """

        self._data = data

    @property
    def error(self):
        """Gets the error of this Envelop.


        :return: The error of this Envelop.
        :rtype: Error
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this Envelop.


        :param error: The error of this Envelop.
        :type error: Error
        """

        self._error = error
