# coding: utf-8

from __future__ import absolute_import

from sarna.routes.api import util
from sarna.routes.api.models.base_model_ import Model


class FindingResume(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, title=None):  # noqa: E501
        """FindingResume - a model defined in OpenAPI

        :param id: The id of this FindingResume.  # noqa: E501
        :type id: int
        :param name: The name of this FindingResume.  # noqa: E501
        :type name: str
        :param title: The title of this FindingResume.  # noqa: E501
        :type title: str
        """
        self.openapi_types = {
            'id': int,
            'name': str,
            'title': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'title': 'title'
        }

        self._id = id
        self._name = name
        self._title = title

    @classmethod
    def from_dict(cls, dikt) -> 'FindingResume':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FindingResume of this FindingResume.  # noqa: E501
        :rtype: FindingResume
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this FindingResume.


        :return: The id of this FindingResume.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this FindingResume.


        :param id: The id of this FindingResume.
        :type id: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this FindingResume.


        :return: The name of this FindingResume.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this FindingResume.


        :param name: The name of this FindingResume.
        :type name: str
        """
        if name is not None and len(name) > 60:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `60`")  # noqa: E501

        self._name = name

    @property
    def title(self):
        """Gets the title of this FindingResume.


        :return: The title of this FindingResume.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this FindingResume.


        :param title: The title of this FindingResume.
        :type title: str
        """
        if title is not None and len(title) > 128:
            raise ValueError("Invalid value for `title`, length must be less than or equal to `128`")  # noqa: E501

        self._title = title
