# coding: utf-8

from __future__ import absolute_import

from sarna.routes.api import util
from sarna.routes.api.models.base_model_ import Model


class FindingRequestBody(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, title=None, status=None, type=None, owasp_category=None, owasp_mobile_category=None,
                 owisam_category=None, tech_risk=None, business_risk=None, exploitability=None, dissemination=None,
                 solution_complexity=None, template=None):  # noqa: E501
        """FindingRequestBody - a model defined in OpenAPI

        :param title: The title of this FindingRequestBody.  # noqa: E501
        :type title: str
        :param status: The status of this FindingRequestBody.  # noqa: E501
        :type status: FindingStatus
        :param type: The type of this FindingRequestBody.  # noqa: E501
        :type type: FindingType
        :param owasp_category: The owasp_category of this FindingRequestBody.  # noqa: E501
        :type owasp_category: OWASPCategory
        :param owasp_mobile_category: The owasp_mobile_category of this FindingRequestBody.  # noqa: E501
        :type owasp_mobile_category: OWASPMobileTop10Category
        :param owisam_category: The owisam_category of this FindingRequestBody.  # noqa: E501
        :type owisam_category: OWISAMCategory
        :param tech_risk: The tech_risk of this FindingRequestBody.  # noqa: E501
        :type tech_risk: Score
        :param business_risk: The business_risk of this FindingRequestBody.  # noqa: E501
        :type business_risk: Score
        :param exploitability: The exploitability of this FindingRequestBody.  # noqa: E501
        :type exploitability: Score
        :param dissemination: The dissemination of this FindingRequestBody.  # noqa: E501
        :type dissemination: Score
        :param solution_complexity: The solution_complexity of this FindingRequestBody.  # noqa: E501
        :type solution_complexity: Score
        :param template: The template of this FindingRequestBody.  # noqa: E501
        :type template: str
        """
        from sarna.routes.api.models import FindingStatus
        from sarna.routes.api.models import FindingType
        from sarna.routes.api.models import OWASPCategory
        from sarna.routes.api.models import OWASPMobileTop10Category
        from sarna.routes.api.models import OWISAMCategory
        from sarna.routes.api.models import Score
        self.openapi_types = {
            'title': str,
            'status': FindingStatus,
            'type': FindingType,
            'owasp_category': OWASPCategory,
            'owasp_mobile_category': OWASPMobileTop10Category,
            'owisam_category': OWISAMCategory,
            'tech_risk': Score,
            'business_risk': Score,
            'exploitability': Score,
            'dissemination': Score,
            'solution_complexity': Score,
            'template': str
        }

        self.attribute_map = {
            'title': 'title',
            'status': 'status',
            'type': 'type',
            'owasp_category': 'owasp_category',
            'owasp_mobile_category': 'owasp_mobile_category',
            'owisam_category': 'owisam_category',
            'tech_risk': 'tech_risk',
            'business_risk': 'business_risk',
            'exploitability': 'exploitability',
            'dissemination': 'dissemination',
            'solution_complexity': 'solution_complexity',
            'template': 'template'
        }

        self._title = title
        self._status = status
        self._type = type
        self._owasp_category = owasp_category
        self._owasp_mobile_category = owasp_mobile_category
        self._owisam_category = owisam_category
        self._tech_risk = tech_risk
        self._business_risk = business_risk
        self._exploitability = exploitability
        self._dissemination = dissemination
        self._solution_complexity = solution_complexity
        self._template = template

    @classmethod
    def from_dict(cls, dikt) -> 'FindingRequestBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FindingRequestBody of this FindingRequestBody.  # noqa: E501
        :rtype: FindingRequestBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self):
        """Gets the title of this FindingRequestBody.


        :return: The title of this FindingRequestBody.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this FindingRequestBody.


        :param title: The title of this FindingRequestBody.
        :type title: str
        """
        if title is not None and len(title) > 128:
            raise ValueError("Invalid value for `title`, length must be less than or equal to `128`")  # noqa: E501

        self._title = title

    @property
    def status(self):
        """Gets the status of this FindingRequestBody.


        :return: The status of this FindingRequestBody.
        :rtype: FindingStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this FindingRequestBody.


        :param status: The status of this FindingRequestBody.
        :type status: FindingStatus
        """

        self._status = status

    @property
    def type(self):
        """Gets the type of this FindingRequestBody.


        :return: The type of this FindingRequestBody.
        :rtype: FindingType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this FindingRequestBody.


        :param type: The type of this FindingRequestBody.
        :type type: FindingType
        """

        self._type = type

    @property
    def owasp_category(self):
        """Gets the owasp_category of this FindingRequestBody.


        :return: The owasp_category of this FindingRequestBody.
        :rtype: OWASPCategory
        """
        return self._owasp_category

    @owasp_category.setter
    def owasp_category(self, owasp_category):
        """Sets the owasp_category of this FindingRequestBody.


        :param owasp_category: The owasp_category of this FindingRequestBody.
        :type owasp_category: OWASPCategory
        """

        self._owasp_category = owasp_category

    @property
    def owasp_mobile_category(self):
        """Gets the owasp_mobile_category of this FindingRequestBody.


        :return: The owasp_mobile_category of this FindingRequestBody.
        :rtype: OWASPMobileTop10Category
        """
        return self._owasp_mobile_category

    @owasp_mobile_category.setter
    def owasp_mobile_category(self, owasp_mobile_category):
        """Sets the owasp_mobile_category of this FindingRequestBody.


        :param owasp_mobile_category: The owasp_mobile_category of this FindingRequestBody.
        :type owasp_mobile_category: OWASPMobileTop10Category
        """

        self._owasp_mobile_category = owasp_mobile_category

    @property
    def owisam_category(self):
        """Gets the owisam_category of this FindingRequestBody.


        :return: The owisam_category of this FindingRequestBody.
        :rtype: OWISAMCategory
        """
        return self._owisam_category

    @owisam_category.setter
    def owisam_category(self, owisam_category):
        """Sets the owisam_category of this FindingRequestBody.


        :param owisam_category: The owisam_category of this FindingRequestBody.
        :type owisam_category: OWISAMCategory
        """

        self._owisam_category = owisam_category

    @property
    def tech_risk(self):
        """Gets the tech_risk of this FindingRequestBody.


        :return: The tech_risk of this FindingRequestBody.
        :rtype: Score
        """
        return self._tech_risk

    @tech_risk.setter
    def tech_risk(self, tech_risk):
        """Sets the tech_risk of this FindingRequestBody.


        :param tech_risk: The tech_risk of this FindingRequestBody.
        :type tech_risk: Score
        """

        self._tech_risk = tech_risk

    @property
    def business_risk(self):
        """Gets the business_risk of this FindingRequestBody.


        :return: The business_risk of this FindingRequestBody.
        :rtype: Score
        """
        return self._business_risk

    @business_risk.setter
    def business_risk(self, business_risk):
        """Sets the business_risk of this FindingRequestBody.


        :param business_risk: The business_risk of this FindingRequestBody.
        :type business_risk: Score
        """

        self._business_risk = business_risk

    @property
    def exploitability(self):
        """Gets the exploitability of this FindingRequestBody.


        :return: The exploitability of this FindingRequestBody.
        :rtype: Score
        """
        return self._exploitability

    @exploitability.setter
    def exploitability(self, exploitability):
        """Sets the exploitability of this FindingRequestBody.


        :param exploitability: The exploitability of this FindingRequestBody.
        :type exploitability: Score
        """

        self._exploitability = exploitability

    @property
    def dissemination(self):
        """Gets the dissemination of this FindingRequestBody.


        :return: The dissemination of this FindingRequestBody.
        :rtype: Score
        """
        return self._dissemination

    @dissemination.setter
    def dissemination(self, dissemination):
        """Sets the dissemination of this FindingRequestBody.


        :param dissemination: The dissemination of this FindingRequestBody.
        :type dissemination: Score
        """

        self._dissemination = dissemination

    @property
    def solution_complexity(self):
        """Gets the solution_complexity of this FindingRequestBody.


        :return: The solution_complexity of this FindingRequestBody.
        :rtype: Score
        """
        return self._solution_complexity

    @solution_complexity.setter
    def solution_complexity(self, solution_complexity):
        """Sets the solution_complexity of this FindingRequestBody.


        :param solution_complexity: The solution_complexity of this FindingRequestBody.
        :type solution_complexity: Score
        """

        self._solution_complexity = solution_complexity

    @property
    def template(self):
        """Gets the template of this FindingRequestBody.


        :return: The template of this FindingRequestBody.
        :rtype: str
        """
        return self._template

    @template.setter
    def template(self, template):
        """Sets the template of this FindingRequestBody.


        :param template: The template of this FindingRequestBody.
        :type template: str
        """
        if template is not None and len(template) > 64:
            raise ValueError("Invalid value for `template`, length must be less than or equal to `64`")  # noqa: E501

        self._template = template
