# coding: utf-8

from __future__ import absolute_import

from sarna.routes.api import util
from sarna.routes.api.models.base_model_ import Model


class FindingType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    WEB = "Web"
    INFRA = "Infra"
    MOBILE = "Mobile"
    WIFI = "WiFi"

    def __init__(self):  # noqa: E501
        """FindingType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'FindingType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FindingType of this FindingType.  # noqa: E501
        :rtype: FindingType
        """
        return util.deserialize_model(dikt, cls)
