# coding: utf-8

from __future__ import absolute_import

from sarna.routes.api import util
from sarna.routes.api.models.base_model_ import Model


class FindingTemplateResume(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, id=None):  # noqa: E501
        """FindingTemplateResume - a model defined in OpenAPI

        :param name: The name of this FindingTemplateResume.  # noqa: E501
        :type name: str
        :param id: The id of this FindingTemplateResume.  # noqa: E501
        :type id: int
        """
        self.openapi_types = {
            'name': str,
            'id': int
        }

        self.attribute_map = {
            'name': 'name',
            'id': 'id'
        }

        self._name = name
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'FindingTemplateResume':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FindingTemplateResume of this FindingTemplateResume.  # noqa: E501
        :rtype: FindingTemplateResume
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this FindingTemplateResume.


        :return: The name of this FindingTemplateResume.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this FindingTemplateResume.


        :param name: The name of this FindingTemplateResume.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) > 64:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `64`")  # noqa: E501

        self._name = name

    @property
    def id(self):
        """Gets the id of this FindingTemplateResume.


        :return: The id of this FindingTemplateResume.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this FindingTemplateResume.


        :param id: The id of this FindingTemplateResume.
        :type id: int
        """

        self._id = id
