# coding: utf-8

from __future__ import absolute_import

from sarna.routes.api import util
from sarna.routes.api.models.base_model_ import Model


class FindingTemplateCreate(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, type=None, owasp_category=None, owasp_mobile_category=None, owisam_category=None,
                 tech_risk=None, business_risk=None, exploitability=None, dissemination=None, solution_complexity=None,
                 lang=None, title=None, definition=None, references=None, description=None):  # noqa: E501
        """FindingTemplateCreate - a model defined in OpenAPI

        :param name: The name of this FindingTemplateCreate.  # noqa: E501
        :type name: str
        :param type: The type of this FindingTemplateCreate.  # noqa: E501
        :type type: FindingType
        :param owasp_category: The owasp_category of this FindingTemplateCreate.  # noqa: E501
        :type owasp_category: OWASPCategory
        :param owasp_mobile_category: The owasp_mobile_category of this FindingTemplateCreate.  # noqa: E501
        :type owasp_mobile_category: OWASPMobileTop10Category
        :param owisam_category: The owisam_category of this FindingTemplateCreate.  # noqa: E501
        :type owisam_category: OWISAMCategory
        :param tech_risk: The tech_risk of this FindingTemplateCreate.  # noqa: E501
        :type tech_risk: Score
        :param business_risk: The business_risk of this FindingTemplateCreate.  # noqa: E501
        :type business_risk: Score
        :param exploitability: The exploitability of this FindingTemplateCreate.  # noqa: E501
        :type exploitability: Score
        :param dissemination: The dissemination of this FindingTemplateCreate.  # noqa: E501
        :type dissemination: Score
        :param solution_complexity: The solution_complexity of this FindingTemplateCreate.  # noqa: E501
        :type solution_complexity: Score
        :param lang: The lang of this FindingTemplateCreate.  # noqa: E501
        :type lang: Language
        :param title: The title of this FindingTemplateCreate.  # noqa: E501
        :type title: str
        :param definition: The definition of this FindingTemplateCreate.  # noqa: E501
        :type definition: str
        :param references: The references of this FindingTemplateCreate.  # noqa: E501
        :type references: str
        :param description: The description of this FindingTemplateCreate.  # noqa: E501
        :type description: str
        """
        from sarna.routes.api.models import FindingType
        from sarna.routes.api.models import OWASPCategory
        from sarna.routes.api.models import OWASPMobileTop10Category
        from sarna.routes.api.models import OWISAMCategory
        from sarna.routes.api.models import Score
        from sarna.routes.api.models import Language
        self.openapi_types = {
            'name': str,
            'type': FindingType,
            'owasp_category': OWASPCategory,
            'owasp_mobile_category': OWASPMobileTop10Category,
            'owisam_category': OWISAMCategory,
            'tech_risk': Score,
            'business_risk': Score,
            'exploitability': Score,
            'dissemination': Score,
            'solution_complexity': Score,
            'lang': Language,
            'title': str,
            'definition': str,
            'references': str,
            'description': str
        }

        self.attribute_map = {
            'name': 'name',
            'type': 'type',
            'owasp_category': 'owasp_category',
            'owasp_mobile_category': 'owasp_mobile_category',
            'owisam_category': 'owisam_category',
            'tech_risk': 'tech_risk',
            'business_risk': 'business_risk',
            'exploitability': 'exploitability',
            'dissemination': 'dissemination',
            'solution_complexity': 'solution_complexity',
            'lang': 'lang',
            'title': 'title',
            'definition': 'definition',
            'references': 'references',
            'description': 'description'
        }

        self._name = name
        self._type = type
        self._owasp_category = owasp_category
        self._owasp_mobile_category = owasp_mobile_category
        self._owisam_category = owisam_category
        self._tech_risk = tech_risk
        self._business_risk = business_risk
        self._exploitability = exploitability
        self._dissemination = dissemination
        self._solution_complexity = solution_complexity
        self._lang = lang
        self._title = title
        self._definition = definition
        self._references = references
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'FindingTemplateCreate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FindingTemplateCreate of this FindingTemplateCreate.  # noqa: E501
        :rtype: FindingTemplateCreate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this FindingTemplateCreate.


        :return: The name of this FindingTemplateCreate.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this FindingTemplateCreate.


        :param name: The name of this FindingTemplateCreate.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) > 64:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `64`")  # noqa: E501

        self._name = name

    @property
    def type(self):
        """Gets the type of this FindingTemplateCreate.


        :return: The type of this FindingTemplateCreate.
        :rtype: FindingType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this FindingTemplateCreate.


        :param type: The type of this FindingTemplateCreate.
        :type type: FindingType
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def owasp_category(self):
        """Gets the owasp_category of this FindingTemplateCreate.


        :return: The owasp_category of this FindingTemplateCreate.
        :rtype: OWASPCategory
        """
        return self._owasp_category

    @owasp_category.setter
    def owasp_category(self, owasp_category):
        """Sets the owasp_category of this FindingTemplateCreate.


        :param owasp_category: The owasp_category of this FindingTemplateCreate.
        :type owasp_category: OWASPCategory
        """

        self._owasp_category = owasp_category

    @property
    def owasp_mobile_category(self):
        """Gets the owasp_mobile_category of this FindingTemplateCreate.


        :return: The owasp_mobile_category of this FindingTemplateCreate.
        :rtype: OWASPMobileTop10Category
        """
        return self._owasp_mobile_category

    @owasp_mobile_category.setter
    def owasp_mobile_category(self, owasp_mobile_category):
        """Sets the owasp_mobile_category of this FindingTemplateCreate.


        :param owasp_mobile_category: The owasp_mobile_category of this FindingTemplateCreate.
        :type owasp_mobile_category: OWASPMobileTop10Category
        """

        self._owasp_mobile_category = owasp_mobile_category

    @property
    def owisam_category(self):
        """Gets the owisam_category of this FindingTemplateCreate.


        :return: The owisam_category of this FindingTemplateCreate.
        :rtype: OWISAMCategory
        """
        return self._owisam_category

    @owisam_category.setter
    def owisam_category(self, owisam_category):
        """Sets the owisam_category of this FindingTemplateCreate.


        :param owisam_category: The owisam_category of this FindingTemplateCreate.
        :type owisam_category: OWISAMCategory
        """

        self._owisam_category = owisam_category

    @property
    def tech_risk(self):
        """Gets the tech_risk of this FindingTemplateCreate.


        :return: The tech_risk of this FindingTemplateCreate.
        :rtype: Score
        """
        return self._tech_risk

    @tech_risk.setter
    def tech_risk(self, tech_risk):
        """Sets the tech_risk of this FindingTemplateCreate.


        :param tech_risk: The tech_risk of this FindingTemplateCreate.
        :type tech_risk: Score
        """
        if tech_risk is None:
            raise ValueError("Invalid value for `tech_risk`, must not be `None`")  # noqa: E501

        self._tech_risk = tech_risk

    @property
    def business_risk(self):
        """Gets the business_risk of this FindingTemplateCreate.


        :return: The business_risk of this FindingTemplateCreate.
        :rtype: Score
        """
        return self._business_risk

    @business_risk.setter
    def business_risk(self, business_risk):
        """Sets the business_risk of this FindingTemplateCreate.


        :param business_risk: The business_risk of this FindingTemplateCreate.
        :type business_risk: Score
        """
        if business_risk is None:
            raise ValueError("Invalid value for `business_risk`, must not be `None`")  # noqa: E501

        self._business_risk = business_risk

    @property
    def exploitability(self):
        """Gets the exploitability of this FindingTemplateCreate.


        :return: The exploitability of this FindingTemplateCreate.
        :rtype: Score
        """
        return self._exploitability

    @exploitability.setter
    def exploitability(self, exploitability):
        """Sets the exploitability of this FindingTemplateCreate.


        :param exploitability: The exploitability of this FindingTemplateCreate.
        :type exploitability: Score
        """
        if exploitability is None:
            raise ValueError("Invalid value for `exploitability`, must not be `None`")  # noqa: E501

        self._exploitability = exploitability

    @property
    def dissemination(self):
        """Gets the dissemination of this FindingTemplateCreate.


        :return: The dissemination of this FindingTemplateCreate.
        :rtype: Score
        """
        return self._dissemination

    @dissemination.setter
    def dissemination(self, dissemination):
        """Sets the dissemination of this FindingTemplateCreate.


        :param dissemination: The dissemination of this FindingTemplateCreate.
        :type dissemination: Score
        """
        if dissemination is None:
            raise ValueError("Invalid value for `dissemination`, must not be `None`")  # noqa: E501

        self._dissemination = dissemination

    @property
    def solution_complexity(self):
        """Gets the solution_complexity of this FindingTemplateCreate.


        :return: The solution_complexity of this FindingTemplateCreate.
        :rtype: Score
        """
        return self._solution_complexity

    @solution_complexity.setter
    def solution_complexity(self, solution_complexity):
        """Sets the solution_complexity of this FindingTemplateCreate.


        :param solution_complexity: The solution_complexity of this FindingTemplateCreate.
        :type solution_complexity: Score
        """
        if solution_complexity is None:
            raise ValueError("Invalid value for `solution_complexity`, must not be `None`")  # noqa: E501

        self._solution_complexity = solution_complexity

    @property
    def lang(self):
        """Gets the lang of this FindingTemplateCreate.


        :return: The lang of this FindingTemplateCreate.
        :rtype: Language
        """
        return self._lang

    @lang.setter
    def lang(self, lang):
        """Sets the lang of this FindingTemplateCreate.


        :param lang: The lang of this FindingTemplateCreate.
        :type lang: Language
        """
        if lang is None:
            raise ValueError("Invalid value for `lang`, must not be `None`")  # noqa: E501

        self._lang = lang

    @property
    def title(self):
        """Gets the title of this FindingTemplateCreate.


        :return: The title of this FindingTemplateCreate.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this FindingTemplateCreate.


        :param title: The title of this FindingTemplateCreate.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501
        if title is not None and len(title) > 128:
            raise ValueError("Invalid value for `title`, length must be less than or equal to `128`")  # noqa: E501

        self._title = title

    @property
    def definition(self):
        """Gets the definition of this FindingTemplateCreate.


        :return: The definition of this FindingTemplateCreate.
        :rtype: str
        """
        return self._definition

    @definition.setter
    def definition(self, definition):
        """Sets the definition of this FindingTemplateCreate.


        :param definition: The definition of this FindingTemplateCreate.
        :type definition: str
        """
        if definition is None:
            raise ValueError("Invalid value for `definition`, must not be `None`")  # noqa: E501

        self._definition = definition

    @property
    def references(self):
        """Gets the references of this FindingTemplateCreate.


        :return: The references of this FindingTemplateCreate.
        :rtype: str
        """
        return self._references

    @references.setter
    def references(self, references):
        """Sets the references of this FindingTemplateCreate.


        :param references: The references of this FindingTemplateCreate.
        :type references: str
        """
        if references is None:
            raise ValueError("Invalid value for `references`, must not be `None`")  # noqa: E501

        self._references = references

    @property
    def description(self):
        """Gets the description of this FindingTemplateCreate.


        :return: The description of this FindingTemplateCreate.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this FindingTemplateCreate.


        :param description: The description of this FindingTemplateCreate.
        :type description: str
        """

        self._description = description
