# coding: utf-8

from __future__ import absolute_import

from sarna.routes.api import util
from sarna.routes.api.models.base_model_ import Model


class OWASPMobileTop10Category(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    M1 = "M1"
    M2 = "M2"
    M3 = "M3"
    M4 = "M4"
    M5 = "M5"
    M6 = "M6"
    M7 = "M7"
    M8 = "M8"
    M9 = "M9"
    M10 = "M10"

    def __init__(self):  # noqa: E501
        """OWASPMobileTop10Category - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'OWASPMobileTop10Category':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OWASPMobileTop10Category of this OWASPMobileTop10Category.  # noqa: E501
        :rtype: OWASPMobileTop10Category
        """
        return util.deserialize_model(dikt, cls)
