# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from sarna.routes.api.models.base_model_ import Model
from sarna.routes.api import util


class OWISAMCategory(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    DI_001 = "DI-001"

    def __init__(self):  # noqa: E501
        """OWISAMCategory - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'OWISAMCategory':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OWISAMCategory of this OWISAMCategory.  # noqa: E501
        :rtype: OWISAMCategory
        """
        return util.deserialize_model(dikt, cls)
