# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from sarna.routes.api.models.base_model_ import Model
from sarna.routes.api import util


class Template(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, description=None):  # noqa: E501
        """Template - a model defined in OpenAPI

        :param name: The name of this Template.  # noqa: E501
        :type name: str
        :param description: The description of this Template.  # noqa: E501
        :type description: str
        """
        self.openapi_types = {
            'name': 'str',
            'description': 'str'
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description'
        }

        self._name = name
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'Template':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Template of this Template.  # noqa: E501
        :rtype: Template
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this Template.


        :return: The name of this Template.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Template.


        :param name: The name of this Template.
        :type name: str
        """
        if name is not None and len(name) > 25:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `25`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this Template.


        :return: The description of this Template.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Template.


        :param description: The description of this Template.
        :type description: str
        """
        if description is not None and len(description) > 128:
            raise ValueError("Invalid value for `description`, length must be less than or equal to `128`")  # noqa: E501

        self._description = description
