# coding: utf-8

from __future__ import absolute_import

from sarna.routes.api import util
from sarna.routes.api.models.base_model_ import Model
from sarna.routes.api.models.user_type import UserType


class User(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, username=None, user_type=None):  # noqa: E501
        """User - a model defined in OpenAPI

        :param username: The username of this User.  # noqa: E501
        :type username: str
        :param user_type: The user_type of this User.  # noqa: E501
        :type user_type: UserType
        """
        self.openapi_types = {
            'username': str,
            'user_type': UserType
        }

        self.attribute_map = {
            'username': 'username',
            'user_type': 'user_type'
        }

        self._username = username
        self._user_type = user_type

    @classmethod
    def from_dict(cls, dikt) -> 'User':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The User of this User.  # noqa: E501
        :rtype: User
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self):
        """Gets the username of this User.


        :return: The username of this User.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this User.


        :param username: The username of this User.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501
        if username is not None and len(username) > 128:
            raise ValueError("Invalid value for `username`, length must be less than or equal to `128`")  # noqa: E501

        self._username = username

    @property
    def user_type(self):
        """Gets the user_type of this User.


        :return: The user_type of this User.
        :rtype: UserType
        """
        return self._user_type

    @user_type.setter
    def user_type(self, user_type):
        """Sets the user_type of this User.


        :param user_type: The user_type of this User.
        :type user_type: UserType
        """

        self._user_type = user_type
