# coding: utf-8

from __future__ import absolute_import

from sarna.routes.api import util
from sarna.routes.api.models.base_model_ import Model


class UserType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    MANAGER = "manager"
    AUDITOR = "auditor"
    TRUSTED_AUDITOR = "trusted_auditor"
    ADMIN = "admin"

    def __init__(self):  # noqa: E501
        """UserType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'UserType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserType of this UserType.  # noqa: E501
        :rtype: UserType
        """
        return util.deserialize_model(dikt, cls)
