# coding: utf-8

from __future__ import absolute_import

from sarna.routes.api import util
from sarna.routes.api.models.base_model_ import Model


class UserName(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """UserName - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'UserName':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserName of this UserName.  # noqa: E501
        :rtype: UserName
        """
        return util.deserialize_model(dikt, cls)
