"""empty message

Revision ID: a1368cd1f179
Revises: 357612dfa45b
Create Date: 2018-08-02 17:33:12.357992

"""
from alembic import op
import sqlalchemy as sa
import sarna


# revision identifiers, used by Alembic.
revision = 'a1368cd1f179'
down_revision = '357612dfa45b'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('access_token', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'user', ['access_token'])
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'access_token')
    # ### end Alembic commands ###
